-- tests/lua/breadcrumb_spec.lua
local Breadcrumb = require("blame.breadcrumb")
local assert = require("luassert")

describe("blame.breadcrumb", function()
	it("initializes a new breadcrumb", function()
		local bc = Breadcrumb:new()
		assert.are.same({}, bc.stack)
		assert.is_nil(bc:current())
	end)

	it("pushes a new item", function()
		local bc = Breadcrumb:new()
		local added = bc:push("hash1")
		assert.is_true(added)
		assert.are.same({ "hash1" }, bc.stack) -- Stack should just have the current item
		assert.are.equal("hash1", bc:current())
	end)

	it("does not push a duplicate item", function()
		local bc = Breadcrumb:new()
		bc:push("hash1")
		local added = bc:push("hash1")
		assert.is_false(added)
		assert.are.same({ "hash1" }, bc.stack)
		assert.are.equal("hash1", bc:current())
	end)

	it("pushes multiple items", function()
		local bc = Breadcrumb:new()
		bc:push("hash1")
		bc:push("hash2")
		assert.are.same({ "hash1", "hash2" }, bc.stack)
		assert.are.equal("hash2", bc:current())
	end)

	it("pops an item", function()
		local bc = Breadcrumb:new()
		bc:push("hash1")
		bc:push("hash2")
		local item = bc:pop() -- item should be the new current, which is hash1
		assert.are.equal("hash2", item)
		assert.are.equal("hash1", bc:current())
		assert.are.same({ "hash1" }, bc.stack)
	end)

	it("returns nil when popping from an empty stack", function()
		local bc = Breadcrumb:new()
		local item = bc:pop()
		assert.is_nil(item)
		assert.is_nil(bc:current())
		assert.are.same({}, bc.stack)
	end)

	it("does not push '00000000' to the stack", function()
		local bc = Breadcrumb:new()
		local added = bc:push("00000000")
		assert.is_false(added)
		assert.are.same({}, bc.stack)
		assert.is_nil(bc:current())
	end)
end)
